### ISSUE TITLE
amos_test failed

### ISSUE THREAD

**Issue by pczzy** [google-research/jestimator#1]
Run amos_test.py  failed 
Envs:
Python: 3.8.13
Jax: 0.3.23

PYTHONPATH=. python3 jestimator/amos_test.py
Traceback (most recent call last):
  File "jestimator/amos_test.py", line 19, in <module>
    from jestimator import amos
  File "/home/super/sina_project/jestimator/jestimator/amos.py", line 56, in <module>
    eta_fn: Callable[Tuple[str, ...], chex.Array],
  File "/home/super/miniconda3/envs/jax/lib/python3.8/typing.py", line 813, in __getitem__
    raise TypeError(f"Callable[args, result]: args must be a list."
TypeError: Callable[args, result]: args must be a list. Got typing.Tuple[str, ...]

**Comment by tianran** [comment]
Hi! It seems that the type checking was not previously set up in my env. Now this issue should be fixed by the new update. Thanks for reporting! Best!
